server:
  appName : Dastak
  appUrl : http://localhost:8000
  internalPort: 8000
  externalPort: 8000
  runMode: debug

logger:
  filePath: ../logs/
  encoding: json
  level: debug
  logger: zap

postgres :
  host : localhost
  port : 5432
  user :  postgres
  password : sH1382@@
  dbName : dastak
  sslMode : disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5


redis:
  host: localhost
  port: 6379
  password: 
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500

password:
  includeChars: true
  includeDigits: true
  minLength: 6
  maxLength: 64
  includeUppercase: true
  includeLowercase: true

jwt:
  secret: "mySecretKey"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 1440
  refreshTokenExpireDuration: 60


Zibal : 
  token : zibal
  callBackUrl : https://localhost:3005